function(enable_code_coverage target_name)
  option(ENABLE_CODE_COVERAGE "Generate code coverage data" OFF)
  if(ENABLE_CODE_COVERAGE)
    if (CMAKE_BUILD_TYPE STREQUAL "Debug")
      target_compile_options(${target_name} INTERFACE --coverage)
      target_link_libraries(${target_name} INTERFACE "--coverage")
    else()
      message(FATAL_ERROR "Code coverage can only be enabled for debug/unoptimized builds")
    endif()
  endif()
endfunction()